version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: memorizador-db
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: memorizador
      MYSQL_USER: admin
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
